修改默认固件大小, 增加x86 iStore编译选项, 增加虚拟机镜像编译

diff --git a/.github/workflows/build-x86-64-23.05.4.yml b/.github/workflows/build-x86-64-23.05.4.yml
--- a/.github/workflows/build-x86-64-23.05.4.yml
+++ b/.github/workflows/build-x86-64-23.05.4.yml
@@ -14,8 +14,17 @@ on:
         default: 'yes'
         type: choice
         options:
-          - 'yes'
-          - 'no'
+        - 'yes'
+        - 'no'
+      include_istore:
+        description: |
+          是否集成 iStore 软件中心
+        required: true
+        default: 'yes'
+        type: choice
+        options:
+        - 'yes'
+        - 'no'
       enable_pppoe:
         description: "是否配置PPPoE拨号信息?"
         required: true
@@ -36,69 +45,88 @@ jobs:
     runs-on: ubuntu-22.04
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+    - name: Checkout code
+      uses: actions/checkout@v3
 
-      - name: Set executable permissions
-        run: chmod +x ${{ github.workspace }}/x86-64/build.sh
-      
-      - name: Validate PPPoE Inputs
-        run: |
-          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
-            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
-              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
-              exit 1
-            fi
+    - name: Set executable permissions
+      run: chmod +x ${{ github.workspace }}/x86-64/build.sh
+
+    - name: Validate PPPoE Inputs
+      run: |
+        if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
+          if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
+            echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
+            exit 1
           fi
+        fi
 
-      - name: Build ImmortalWrt-x86-64-efi
-        run: |
-          profiles="${{ github.event.inputs.profile }}"
-          include_docker="${{ github.event.inputs.include_docker }}"
-          
-          IFS=',' read -r -a profile_array <<< "$profiles"
-          
-          for profile in "${profile_array[@]}"; do
-            echo "Building for profile: $profile"
-            
-            docker run --rm -i \
-              --user root \
-              -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
-              -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
-              -v "${{ github.workspace }}/x86-64/imm.config:/home/build/immortalwrt/.config" \
-              -v "${{ github.workspace }}/x86-64/build.sh:/home/build/immortalwrt/build.sh" \
-              -e PROFILE=$profile \
-              -e INCLUDE_DOCKER=$include_docker \
-              -e ENABLE_PPPOE=${{ inputs.enable_pppoe }} \
-              -e PPPOE_ACCOUNT=${{ inputs.pppoe_account }} \
-              -e PPPOE_PASSWORD=${{ inputs.pppoe_password }} \
-              immortalwrt/imagebuilder:x86-64-openwrt-23.05.4 /bin/bash /home/build/immortalwrt/build.sh
-          done
-      
-      - name: Generate Firmware SHA-256
-        run: |
-          cp ${{ github.workspace }}/bin/targets/x86/64/immortalwrt-23.05.4-x86-64-generic-squashfs-combined-efi.img.gz ${{ github.workspace }}
-          sha256sum immortalwrt-23.05.4-x86-64-generic-squashfs-combined-efi.img.gz > immortalwrt-23.05.4-x86-64-generic-squashfs-combined-efi.img.gz.sha256
-          sha256sum -c immortalwrt-23.05.4-x86-64-generic-squashfs-combined-efi.img.gz.sha256
+    - name: Build ImmortalWrt-x86-64-efi
+      run: |
+        profiles="${{ github.event.inputs.profile }}"
+        include_docker="${{ github.event.inputs.include_docker }}"
+        include_istore="${{ github.event.inputs.include_istore }}"
+        IFS=',' read -r -a profile_array <<< "$profiles"
 
-      - name: Create info
-        run: |
-          if [ "${{ github.event.inputs.include_docker }}" == "yes" ]; then
-            extra_content="#### 默认带docker"
-            echo -e "\n $extra_content" >> ${{ github.workspace }}/info.md
-          else
-            echo -e "NO docker"
-          fi
+        for profile in "${profile_array[@]}"; do
+          echo "Building for profile: $profile"
 
-      - name: Upload ImmortWrt as release assets
-        uses: softprops/action-gh-release@v2.2.1
-        with:
-          tag_name: Autobuild-x86-64
-          body_path: ${{ github.workspace }}/info.md
-          files: |
-            ${{ github.workspace }}/immortalwrt-23.05.4-x86-64-generic-squashfs-combined-efi.img.gz
-            ${{ github.workspace }}/immortalwrt-23.05.4-x86-64-generic-squashfs-combined-efi.img.gz.sha256
-          token: ${{ secrets.GITHUB_TOKEN }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          docker run --rm -i \
+            --user root \
+            -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
+            -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
+            -v "${{ github.workspace }}/x86-64/imm.config:/home/build/immortalwrt/.config" \
+            -v "${{ github.workspace }}/x86-64/build.sh:/home/build/immortalwrt/build.sh" \
+            -e PROFILE=$profile \
+            -e INCLUDE_DOCKER=$include_docker \
+            -e INCLUDE_ISTORE=$include_istore \
+            -e ENABLE_PPPOE=${{ inputs.enable_pppoe }} \
+            -e PPPOE_ACCOUNT=${{ inputs.pppoe_account }} \
+            -e PPPOE_PASSWORD=${{ inputs.pppoe_password }} \
+            immortalwrt/imagebuilder:x86-64-openwrt-23.05.4 /bin/bash /home/build/immortalwrt/build.sh
+        done
 
+    - name: Generate Firmware SHA-256
+      run: |
+        cp ${{ github.workspace }}/bin/targets/x86/64/*squashfs-combined-efi.img.gz ${{ github.workspace }}
+        cp ${{ github.workspace }}/bin/targets/x86/64/*squashfs-combined-efi.vmdk ${{ github.workspace }}
+        cp ${{ github.workspace }}/bin/targets/x86/64/*squashfs-combined-efi.vhdx ${{ github.workspace }}
+        cp ${{ github.workspace }}/bin/targets/x86/64/*squashfs-combined-efi.vdi ${{ github.workspace }}
+        cp ${{ github.workspace }}/bin/targets/x86/64/*squashfs-combined-efi.qcow2 ${{ github.workspace }}
+        cp ${{ github.workspace }}/bin/targets/x86/64/*generic-image-efi.iso ${{ github.workspace }}
+        for file in \
+          *squashfs-combined-efi.img.gz \
+          *squashfs-combined-efi.vmdk \
+          *squashfs-combined-efi.vhdx \
+          *squashfs-combined-efi.vdi \
+          *squashfs-combined-efi.qcow2 \
+          *generic-image-efi.iso
+        do
+          sha256sum "$file" > "$file.sha256"
+          sha256sum -c "$file.sha256"
+        done
+
+    - name: Create info
+      run: |
+        if [ "${{ github.event.inputs.include_docker }}" == "yes" ]; then
+          extra_content="#### 默认带docker"
+          echo -e "\n $extra_content" >> ${{ github.workspace }}/info.md
+        else
+          echo -e "NO docker"
+        fi
+
+    - name: Upload ImmortWrt as release assets
+      uses: softprops/action-gh-release@v2.2.1
+      with:
+        tag_name: Autobuild-x86-64
+        body_path: ${{ github.workspace }}/info.md
+        files: |
+          ${{ github.workspace }}/*squashfs-combined-efi.img.gz
+          ${{ github.workspace }}/*squashfs-combined-efi.vmdk
+          ${{ github.workspace }}/*squashfs-combined-efi.vhdx
+          ${{ github.workspace }}/*squashfs-combined-efi.vdi
+          ${{ github.workspace }}/*squashfs-combined-efi.qcow2
+          ${{ github.workspace }}/*generic-image-efi.iso
+          ${{ github.workspace }}/*.sha256
+        token: ${{ secrets.GITHUB_TOKEN }}
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
